const audioData = [
  {
    id: 1,
    label: "a",
    file: require("../assets/audio/single-letters/a.mp3"),
    desc: '"Far", like dentist',
    underline: [2, 3],
  },
  {
    id: 2,
    label: "ă",
    file: require("../assets/audio/single-letters/ă.mp3"),
    desc: '"Apple", higher pitch than a, "smile" literally',
    underline: [1, 2],
  },
  {
    id: 3,
    label: "â",
    file: require("../assets/audio/single-letters/â.mp3"),
    desc: '"Sun", relaxed',
    underline: [2, 3],
  },
  {
    id: 4,
    label: "b",
    file: require("../assets/audio/single-letters/b.mp3"),
    desc: '"Bar", "ba", short "buh" sound',
    underline: [1, 2],
  },
  {
    id: 5,
    label: "c",
    file: require("../assets/audio/single-letters/c.mp3"),
    desc: '"Car", "con", unaspirated via. tongue back of throat',
    underline: [1, 2],
  },
  {
    id: 6,
    label: "d",
    file: require("../assets/audio/single-letters/d.mp3"),
    desc: '"You", "Dê", south accent',
    underline: [1, 2],
  },
  {
    id: 7,
    label: "đ",
    file: require("../assets/audio/single-letters/đ.mp3"),
    desc: '"Do", "Đen"',
    underline: [1, 2],
  },
  {
    id: 8,
    label: "e",
    file: require("../assets/audio/single-letters/e.mp3"),
    desc: '"Empty"',
    underline: [1, 2],
  },
  {
    id: 9,
    label: "ê",
    file: require("../assets/audio/single-letters/ê.mp3"),
    desc: '"Hey", tongue bottom tip behind teeth rises',
    underline: [2, 3],
  },
  {
    id: 10,
    label: "g",
    file: require("../assets/audio/single-letters/g.mp3"),
    desc: '"Go", "Gan", tongue back of throat',
    underline: [1, 2],
  },
  {
    id: 11,
    label: "h",
    file: require("../assets/audio/single-letters/h.mp3"),
    desc: '"Hot", "Ho"',
    underline: [1, 2],
  },
  {
    id: 12,
    label: "i",
    file: require("../assets/audio/single-letters/i.mp3"),
    desc: '"See"',
    underline: [2, 4],
  },
  {
    id: 13,
    label: "k",
    file: require("../assets/audio/single-letters/k.mp3"),
    desc: '"Car", "Kem", notably aspirated vs "c"',
    underline: [1, 2],
  },
  {
    id: 14,
    label: "l",
    file: require("../assets/audio/single-letters/l.mp3"),
    desc: '"Land", "Lăn"',
    underline: [1, 2],
  },
  {
    id: 15,
    label: "m",
    file: require("../assets/audio/single-letters/m.mp3"),
    desc: '"Mom", "Mua"',
    underline: [1, 2],
  },
  {
    id: 16,
    label: "n",
    file: require("../assets/audio/single-letters/n.mp3"),
    desc: '"No", "Năm"',
    underline: [1, 2],
  },
  {
    id: 17,
    label: "o",
    file: require("../assets/audio/single-letters/o.mp3"),
    desc: '"Saw"',
    underline: [2, 4],
  },
  {
    id: 18,
    label: "ô",
    file: require("../assets/audio/single-letters/ô.mp3"),
    desc: '"Hope", tongue pulled back low position',
    underline: [2, 3],
  },
  {
    id: 19,
    label: "ơ",
    file: require("../assets/audio/single-letters/ơ.mp3"),
    desc: '"Familiar", more "uhh" sound',
    underline: [2, 3],
  },
  {
    id: 20,
    label: "p",
    file: require("../assets/audio/single-letters/p.mp3"),
    desc: 'More like "bin" instead of "pin"; unaspirated',
    underline: [11, 12],
  },
  {
    id: 21,
    label: "q",
    file: require("../assets/audio/single-letters/q.mp3"),
    desc: '"Why", "Qua", south accent',
    underline: [1, 3],
  },
  {
    id: 22,
    label: "r",
    file: require("../assets/audio/single-letters/r.mp3"),
    desc: '"Red", "ra", central accent no roll',
    underline: [1, 2],
  },
  {
    id: 23,
    label: "s",
    file: require("../assets/audio/single-letters/s.mp3"),
    desc: '"Sit", "Sư"',
    underline: [1, 2],
  },
  {
    id: 24,
    label: "t",
    file: require("../assets/audio/single-letters/t.mp3"),
    desc: 'Strong "time", unaspirated, "To"',
    underline: [8, 9],
  },
  {
    id: 25,
    label: "u",
    file: require("../assets/audio/single-letters/u.mp3"),
    desc: '"Moo", tongue pulled away from lower teeth',
    underline: [2, 4],
  },
  {
    id: 26,
    label: "ư",
    file: require("../assets/audio/single-letters/ư.mp3"),
    desc: '"Uuoo", sound not in English',
    underline: [1, 5],
  },
  {
    id: 27,
    label: "v",
    file: require("../assets/audio/single-letters/v.mp3"),
    desc: '"Very", "voi", south accent',
    underline: [1, 2],
  },
  {
    id: 28,
    label: "x",
    file: require("../assets/audio/single-letters/x.mp3"),
    desc: '"Sit", "Xa", identical to "s?"',
    underline: [1, 2],
  },
  {
    id: 29,
    label: "y",
    file: require("../assets/audio/single-letters/y.mp3"),
    desc: '"Voi", similar to "i," but bite tongue with molars',
    underline: [],
  },
];

const examples = [];

export default audioData;
