const alphabetData = [
  {
    id: 1,
    label: "a",
    desc: "[ahh]",
    underline: [2, 4],
  },
  {
    id: 2,
    label: "ă",
    desc: "[ah?]",
    underline: [2, 4],
  },
  {
    id: 3,
    label: "â",
    desc: "[uh?]",
    underline: [2, 4],
  },
  {
    id: 4,
    label: "b",
    desc: "[buh]",
    underline: [2, 4],
  },
  {
    id: 5,
    label: "c",
    desc: "[cuh], unaspirated via. tongue back of throat",
    underline: [2, 4],
  },
  {
    id: 6,
    label: "d",
    desc: "[yuh]",
    underline: [2, 4],
  },
  {
    id: 7,
    label: "đ",
    desc: "[duh]",
    underline: [2, 4],
  },
  {
    id: 8,
    label: "e",
    desc: '[ea], like Norwegian "e"',
    underline: [2, 3],
  },
  {
    id: 9,
    label: "ê",
    desc: '[a], like sharp higher pitch English alphabet "a"',
    underline: [2, 2],
  },
  {
    id: 10,
    label: "g",
    desc: "[guh], tongue back of throat",
    underline: [2, 4],
  },
  {
    id: 11,
    label: "h",
    desc: "[hak], almost silent h",
    underline: [2, 4],
  },
  {
    id: 12,
    label: "i",
    desc: '[ee], "see"',
    underline: [2, 3],
  },
  {
    id: 13,
    label: "k",
    desc: '[ca], notably aspirated vs "c"',
    underline: [2, 3],
  },
  {
    id: 14,
    label: "l",
    desc: '[luh]"',
    underline: [2, 4],
  },
  {
    id: 15,
    label: "m",
    desc: "[muh]",
    underline: [2, 4],
  },
  {
    id: 16,
    label: "n",
    desc: "[nuh]",
    underline: [2, 4],
  },
  {
    id: 17,
    label: "o",
    desc: "[awe]",
    underline: [2, 4],
  },
  {
    id: 18,
    label: "ô",
    desc: "[oh], higher pitch",
    underline: [2, 3],
  },
  {
    id: 19,
    label: "ơ",
    desc: "[uh], higher pitch still",
    underline: [2, 3],
  },
  {
    id: 10,
    label: "p",
    desc: "[puh], unaspirated while still English p lips",
    underline: [2, 4],
  },
  {
    id: 21,
    label: "q",
    desc: "[why]",
    underline: [2, 4],
  },
  {
    id: 22,
    label: "r",
    desc: '[ruh]", no roll',
    underline: [2, 5],
  },
  {
    id: 23,
    label: "s",
    desc: "[shuh]",
    underline: [2, 5],
  },
  {
    id: 24,
    label: "t",
    desc: "[tuh], strong unaspirated  t",
    underline: [2, 4],
  },
  {
    id: 25,
    label: "u",
    desc: "[oo], tongue pulled away from lower teeth",
    underline: [2, 3],
  },
  {
    id: 26,
    label: "ư",
    desc: 'Norwegian [u]", higher pitch',
    underline: [12, 12],
  },
  {
    id: 27,
    label: "v",
    desc: "[vuh]",
    underline: [2, 4],
  },
  {
    id: 28,
    label: "x",
    desc: "[suh]",
    underline: [2, 4],
  },
  {
    id: 29,
    label: "y",
    desc: '[ee], similar to "i", Norwegian "y," bite tongue with molars',
    underline: [2, 3],
  },
];

export default alphabetData;
