const alphabetData = [
  {
    id: 1,
    label: "a",
    file: require("../assets/audio/singleLetters/a.mp3"),
    desc: "[ahh]",
    underline: [2, 4],
  },
  {
    id: 2,
    label: "ă",
    file: require("../assets/audio/singleLetters/ă.mp3"),
    desc: "[ah?]",
    underline: [2, 4],
  },
  {
    id: 3,
    label: "â",
    file: require("../assets/audio/singleLetters/â.mp3"),
    desc: "[uh?]",
    underline: [2, 4],
  },
  {
    id: 4,
    label: "b",
    file: require("../assets/audio/singleLetters/b.mp3"),
    desc: "[buh]",
    underline: [2, 4],
  },
  {
    id: 5,
    label: "c",
    file: require("../assets/audio/singleLetters/c.mp3"),
    desc: "[cuh], unaspirated via. tongue back of throat",
    underline: [2, 4],
  },
  {
    id: 6,
    label: "d",
    file: require("../assets/audio/singleLetters/d.mp3"),
    desc: "[yuh]",
    underline: [2, 4],
  },
  {
    id: 7,
    label: "đ",
    file: require("../assets/audio/singleLetters/đ.mp3"),
    desc: "[duh]",
    underline: [2, 4],
  },
  {
    id: 8,
    label: "e",
    file: require("../assets/audio/singleLetters/e.mp3"),
    desc: '[ea], like Norwegian "e"',
    underline: [2, 3],
  },
  {
    id: 9,
    label: "ê",
    file: require("../assets/audio/singleLetters/ê.mp3"),
    desc: '[a], like sharp higher pitch English alphabet "a"',
    underline: [2, 2],
  },
  {
    id: 10,
    label: "g",
    file: require("../assets/audio/singleLetters/g.mp3"),
    desc: "[guh], tongue back of throat",
    underline: [2, 4],
  },
  {
    id: 11,
    label: "h",
    file: require("../assets/audio/singleLetters/h.mp3"),
    desc: "[huh]",
    underline: [2, 4],
  },
  {
    id: 12,
    label: "i",
    file: require("../assets/audio/singleLetters/i.mp3"),
    desc: '[ee], "see"',
    underline: [2, 3],
  },
  {
    id: 13,
    label: "k",
    file: require("../assets/audio/singleLetters/k.mp3"),
    desc: '[ca], notably aspirated vs "c"',
    underline: [2, 3],
  },
  {
    id: 14,
    label: "l",
    file: require("../assets/audio/singleLetters/l.mp3"),
    desc: '[luh]"',
    underline: [2, 4],
  },
  {
    id: 15,
    label: "m",
    file: require("../assets/audio/singleLetters/m.mp3"),
    desc: "[muh]",
    underline: [2, 4],
  },
  {
    id: 16,
    label: "n",
    file: require("../assets/audio/singleLetters/n.mp3"),
    desc: "[nuh]",
    underline: [2, 4],
  },
  {
    id: 17,
    label: "o",
    file: require("../assets/audio/singleLetters/o.mp3"),
    desc: "[awe]",
    underline: [2, 4],
  },
  {
    id: 18,
    label: "ô",
    file: require("../assets/audio/singleLetters/ô.mp3"),
    desc: "[oh], higher pitch",
    underline: [2, 3],
  },
  {
    id: 19,
    label: "ơ",
    file: require("../assets/audio/singleLetters/ơ.mp3"),
    desc: "[uh], higher pitch still",
    underline: [2, 3],
  },
  {
    id: 10,
    label: "p",
    file: require("../assets/audio/singleLetters/p.mp3"),
    desc: "[puh], unaspirated",
    underline: [2, 4],
  },
  {
    id: 21,
    label: "q",
    file: require("../assets/audio/singleLetters/q.mp3"),
    desc: "[why]",
    underline: [2, 4],
  },
  {
    id: 22,
    label: "r",
    file: require("../assets/audio/singleLetters/r.mp3"),
    desc: '[ruh]", no roll',
    underline: [2, 5],
  },
  {
    id: 23,
    label: "s",
    file: require("../assets/audio/singleLetters/s.mp3"),
    desc: "[shuh]",
    underline: [2, 5],
  },
  {
    id: 24,
    label: "t",
    file: require("../assets/audio/singleLetters/t.mp3"),
    desc: "[tuh], strong unaspirated  t",
    underline: [2, 4],
  },
  {
    id: 25,
    label: "u",
    file: require("../assets/audio/singleLetters/u.mp3"),
    desc: "[oo], tongue pulled away from lower teeth",
    underline: [2, 3],
  },
  {
    id: 26,
    label: "ư",
    file: require("../assets/audio/singleLetters/ư.mp3"),
    desc: 'Norwegian [u]", higher pitch',
    underline: [12, 12],
  },
  {
    id: 27,
    label: "v",
    file: require("../assets/audio/singleLetters/v.mp3"),
    desc: "[vuh]",
    underline: [2, 4],
  },
  {
    id: 28,
    label: "x",
    file: require("../assets/audio/singleLetters/x.mp3"),
    desc: "[suh]",
    underline: [2, 4],
  },
  {
    id: 29,
    label: "y",
    file: require("../assets/audio/singleLetters/y.mp3"),
    desc: '[ee], similar to "i", Norwegian "y," bite tongue with molars',
    underline: [2, 3],
  },
];

export default alphabetData;
