const consonantClustersData = [
  {
    id: 1,
    label: "ch",
    file: require("../assets/audio/consonantClusters/ch.mp3"),
    desc: '[jhyuh], Vietnamese "tr + d (south)," "k" if at end of word',
    underline: [2, 6],
  },
  {
    id: 2,
    label: "gh",
    file: require("../assets/audio/consonantClusters/gh.mp3"),
    desc: '[guh], same as Vietnamese "g"',
    underline: [2, 4],
  },
  {
    id: 3,
    label: "gi",
    file: require("../assets/audio/consonantClusters/gi.mp3"),
    desc: '[juh], English "j", south "j" (like Vietnamese "d"), north "z"',
    underline: [2, 4],
  },
  {
    id: 4,
    label: "kh",
    file: require("../assets/audio/consonantClusters/kh.mp3"),
    desc: '[khuh], slight back throat rumble into an "huh"',
    underline: [2, 5],
  },
  {
    id: 5,
    label: "nh",
    file: require("../assets/audio/consonantClusters/nh.mp3"),
    desc: "[nyuh]",
    underline: [2, 5],
  },
  {
    id: 6,
    label: "ng",
    file: require("../assets/audio/consonantClusters/ng.mp3"),
    desc: "[nn-guh], hold back of tongue",
    underline: [2, 7],
  },
  {
    id: 7,
    label: "ngh",
    file: require("../assets/audio/consonantClusters/ngh.mp3"),
    desc: 'Same as "ng", [nn-guh], hold back of tongue"',
    underline: [16, 21],
  },
  {
    id: 8,
    label: "ph",
    file: require("../assets/audio/consonantClusters/ph.mp3"),
    desc: '[fuh], like English "funky"',
    underline: [2, 4],
  },
  {
    id: 9,
    label: "qu",
    file: require("../assets/audio/consonantClusters/qu.mp3"),
    desc: '[wha], from English "what"',
    underline: [2, 4],
  },
  {
    id: 10,
    label: "th",
    file: require("../assets/audio/consonantClusters/th.mp3"),
    desc: '[t-huh], aspirated, less explosive than English "t" which is unaspirated',
    underline: [2, 6],
  },
  {
    id: 11,
    label: "tr",
    file: require("../assets/audio/consonantClusters/tr.mp3"),
    desc: '[jruh], kind of like English "jr"',
    underline: [2, 5],
  },
];

export default consonantClustersData;
