const diphthongsData = [
  {
    id: 1,
    label: "ai",
    file: require("../assets/audio/diphthongs/ai.mp3"),
    desc: "[ai]",
    underline: [1, 2],
  },
  {
    id: 2,
    label: "ao",
    file: require("../assets/audio/diphthongs/ao.mp3"),
    desc: "[ao]",
    underline: [1, 2],
  },
  {
    id: 3,
    label: "au",
    file: require("../assets/audio/diphthongs/au.mp3"),
    desc: "[au]",
    underline: [1, 2],
  },
  {
    id: 4,
    label: "ay",
    file: require("../assets/audio/diphthongs/ay.mp3"),
    desc: "[ay]",
    underline: [1, 2],
  },
  {
    id: 5,
    label: "âu",
    file: require("../assets/audio/diphthongs/âu.mp3"),
    desc: "[âu]",
    underline: [1, 2],
  },
  {
    id: 6,
    label: "ây",
    file: require("../assets/audio/diphthongs/ăy.mp3"),
    desc: "[ăy]",
    underline: [1, 2],
  },
  {
    id: 7,
    label: "ia",
    file: require("../assets/audio/diphthongs/ia.mp3"),
    desc: "[ia]",
    underline: [1, 2],
  },
  {
    id: 8,
    label: "iê",
    file: require("../assets/audio/diphthongs/iê.mp3"),
    desc: "[iê]",
    underline: [1, 2],
  },
  {
    id: 9,
    label: "yê",
    file: require("../assets/audio/diphthongs/yê.mp3"),
    desc: "[yê]",
    underline: [1, 2],
  },
  {
    id: 10,
    label: "eo",
    file: require("../assets/audio/diphthongs/eo.mp3"),
    desc: "[eo]",
    underline: [1, 2],
  },
  {
    id: 11,
    label: "êu",
    file: require("../assets/audio/diphthongs/êu.mp3"),
    desc: "[êu]",
    underline: [1, 2],
  },
  {
    id: 12,
    label: "oa",
    file: require("../assets/audio/diphthongs/oa.mp3"),
    desc: "[oa]",
    underline: [1, 2],
  },
  {
    id: 13,
    label: "oă",
    file: require("../assets/audio/diphthongs/oă.mp3"),
    desc: "[oă]",
    underline: [1, 2],
  },
  {
    id: 14,
    label: "oe",
    file: require("../assets/audio/diphthongs/oe.mp3"),
    desc: "[oe]",
    underline: [1, 2],
  },
  {
    id: 15,
    label: "oi",
    file: require("../assets/audio/diphthongs/oi.mp3"),
    desc: "[oi]",
    underline: [1, 2],
  },
  {
    id: 16,
    label: "ôi",
    file: require("../assets/audio/diphthongs/ôi.mp3"),
    desc: "[ôi]",
    underline: [1, 2],
  },
  {
    id: 17,
    label: "ơi",
    file: require("../assets/audio/diphthongs/ơi.mp3"),
    desc: "[ơi]",
    underline: [1, 2],
  },
  {
    id: 18,
    label: "ua",
    file: require("../assets/audio/diphthongs/ua.mp3"),
    desc: "[ua]",
    underline: [1, 2],
  },
  {
    id: 19,
    label: "uô",
    file: require("../assets/audio/diphthongs/uô.mp3"),
    desc: "[uô]",
    underline: [1, 2],
  },
  {
    id: 20,
    label: "uâ",
    file: require("../assets/audio/diphthongs/uâ.mp3"),
    desc: "[uâ]",
    underline: [1, 2],
  },
  {
    id: 21,
    label: "uê",
    file: require("../assets/audio/diphthongs/uê.mp3"),
    desc: "[uê]",
    underline: [1, 2],
  },
  {
    id: 22,
    label: "ui",
    file: require("../assets/audio/diphthongs/ui.mp3"),
    desc: "[ui]",
    underline: [1, 2],
  },
  {
    id: 23,
    label: "uy",
    file: require("../assets/audio/diphthongs/uy.mp3"),
    desc: "[uy]",
    underline: [1, 2],
  },
  {
    id: 24,
    label: "ưa",
    file: require("../assets/audio/diphthongs/ưa.mp3"),
    desc: "[ưa]",
    underline: [1, 2],
  },
  {
    id: 25,
    label: "ươ",
    file: require("../assets/audio/diphthongs/ươ.mp3"),
    desc: "[ươ]",
    underline: [1, 2],
  },
  {
    id: 26,
    label: "ưi",
    file: require("../assets/audio/diphthongs/ưi.mp3"),
    desc: "[ưi]",
    underline: [1, 2],
  },
  {
    id: 27,
    label: "ưu",
    file: require("../assets/audio/diphthongs/ưu.mp3"),
    desc: "[ưu]",
    underline: [1, 2],
  },
];

export default diphthongsData;
