const audioMap: { [key: string]: any } = {
  a: require("../assets/audio/single-letters/a.mp3"),
  ă: require("../assets/audio/single-letters/ă.mp3"),
  â: require("../assets/audio/single-letters/â.mp3"),
  b: require("../assets/audio/single-letters/b.mp3"),
  c: require("../assets/audio/single-letters/c.mp3"),
  d: require("../assets/audio/single-letters/d.mp3"),
  đ: require("../assets/audio/single-letters/đ.mp3"),
  e: require("../assets/audio/single-letters/e.mp3"),
  ê: require("../assets/audio/single-letters/ê.mp3"),
  g: require("../assets/audio/single-letters/g.mp3"),
  h: require("../assets/audio/single-letters/h.mp3"),
  i: require("../assets/audio/single-letters/i.mp3"),
  k: require("../assets/audio/single-letters/k.mp3"),
  l: require("../assets/audio/single-letters/l.mp3"),
  m: require("../assets/audio/single-letters/m.mp3"),
  n: require("../assets/audio/single-letters/n.mp3"),
  o: require("../assets/audio/single-letters/o.mp3"),
  ô: require("../assets/audio/single-letters/ô.mp3"),
  ơ: require("../assets/audio/single-letters/ơ.mp3"),
  p: require("../assets/audio/single-letters/p.mp3"),
  q: require("../assets/audio/single-letters/q.mp3"),
  r: require("../assets/audio/single-letters/r.mp3"),
  s: require("../assets/audio/single-letters/s.mp3"),
  t: require("../assets/audio/single-letters/t.mp3"),
  u: require("../assets/audio/single-letters/u.mp3"),
  ư: require("../assets/audio/single-letters/ư.mp3"),
  v: require("../assets/audio/single-letters/v.mp3"),
  x: require("../assets/audio/single-letters/x.mp3"),
  y: require("../assets/audio/single-letters/y.mp3"),
};

export default audioMap;
